- name: create db container
  containers.podman.podman_container:
    name: backup_remote
    state: present
    image: postgres:alpine
    ports:
      - "5432:5432"
    env:
      POSTGRES_DB: "backup_remote"
      POSTGRES_PASSWORD: "{{postgres_password}}"
